### ISSUE TITLE
Actividad 7. Linea del tiempo de la web 1.0, 2.0 y 3.0

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-7-AdriHernandez-Martinez0863#1]
[LINEA DEL TIEMPO DE LA WEB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-AdriHernandez-Martinez0863/files/9845336/LINEA.DEL.TIEMPO.DE.LA.WEB.pdf)

**Comment by Jaczibeth** [comment]
del 20% obtuviste un 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
